#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run postgrey?
if [ "${ENABLE_POSTGREY}" = "true" ]; then
    s6-notifyoncheck \
        -s 1000 \
        -t 1000 \
        -n 0 \
        -c "/usr/local/bin/check_postgrey.sh" \
        postgrey \
            --hostname="${POSTFIX_MYHOSTNAME}" \
            --pidfile=/var/run/postgrey.pid \
            --inet=127.0.0.1:10023 \
            --user=postgrey \
            --dbdir=/var/spool/postfix/postgrey \
            --whitelist-clients=/opt/postgrey/postgrey_whitelist_clients \
            --whitelist-recipients=/opt/postgrey/postgrey_whitelist_recipients \
            --whitelist-clients=/etc/postgrey/postgrey_whitelist_clients.local \
            --whitelist-recipients=/etc/postgrey/postgrey_whitelist_recipients.local \
            --greylist-text="Service unavailable. Please try again later." \
            2>&1 | awk -W Interactive '{print "[postgrey] " $0}'
else
    sleep 86400
    exit 0
fi
