version: 2

updates:
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: monthly
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "mikenye"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - "mikenye"