#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

# Wait for clamd, opendkim, clamav-milter
s6-svwait -U /run/s6/services/clamd /run/s6/services/opendkim /run/s6/services/clamav-milter /run/s6/services/postgrey /run/s6/services/syslog

s6-notifyoncheck \
        -s 1000 \
        -t 1000 \
        -n 0 \
        -c "/usr/local/bin/check_postfix.sh" \
        /usr/sbin/postfix start-fg \
        2>&1 | awk -W Interactive '{print "[postfix] " $0}'
