#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

if [ "${ENABLE_CLAMAV}" = "true" ]; then
    bash /wait_for_clamav_milter.sh | awk -W Interactive '{print "[startup] " $0}'
fi

if [ "${ENABLE_OPENDKIM}" = "true" ]; then
    bash /wait_for_opendkim_milter.sh | awk -W Interactive '{print "[startup] " $0}'
fi

if [ "${ENABLE_POSTGREY}" = "true" ]; then
    bash /wait_for_postgrey.sh | awk -W Interactive '{print "[startup] " $0}'
fi

echo "Dependent processes are ready, starting postfix..." | awk -W Interactive '{print "[startup] " $0}'

echo "Waiting for prerequisite services before starting postfix..."
#s6-svwait -U /run/s6/services/clamd

#s6-notifyoncheck \
#        -s 1000 \
#        -t 1000 \
#        -n 0 \
#        -c "postfix status"
        /usr/sbin/postfix start-fg \
        2>&1 | awk -W Interactive '{print "[postfix] " $0}'
