#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

if [ "${ENABLE_CLAMAV}" = "true" ]; then
    pgrep clamav-milter > /dev/null
    if [ "$?" -ne "0" ]; then
        echo "Waiting for clamav-milter..."
        sleep 1
        exit 0
    fi
fi

if [ "${ENABLE_OPENDKIM}" = "true" ]; then
    pgrep opendkim > /dev/null
    if [ "$?" -ne "0" ]; then
        echo "Waiting for opendkim..."
        sleep 1
        exit 0
    fi
fi

exec \
    /usr/sbin/postfix start-fg \
    2>&1 | awk -W Interactive '{print "[postfix] " $0}'
