#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run freshclam?
if [ "${ENABLE_CLAMAV}" = "true" ]; then

    # Random sleep for up to an hour
    sleep $(( ( RANDOM % 3600 ) + 1 ))s

    freshclam \
        --config-file="${CLAMAV_FRESHCLAMCONF_FILE}" \
        --stdout \
        --foreground \
        --daemon \
        | awk -W Interactive '{print "[freshclam] " $0}'
else
    sleep 86400
    exit 0
fi
