#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

exec \
    /usr/sbin/opendkim \
      -u opendkim \
      -f \
      -v \
      -x /etc/opendkim.conf \
    2>&1 | awk -W Interactive '{print "[opendkim] " $0}'
