#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

# Do we run opendkim?
if [ "${ENABLE_OPENDKIM}" = "true" ]; then
    /usr/sbin/opendkim \
      -f \
      -x /etc/opendkim.conf \
      2>&1 | awk -W Interactive '{print "[opendkim] " $0}'
else
    sleep 86400
    exit 0
fi



    
