#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run clamd?
if [ "${ENABLE_CLAMAV}" = "true" ]; then

    # Wait for clamd & postfix
    s6-svwait -U /run/s6/services/clamd /run/s6/services/postfix

    s6-notifyoncheck \
        -s 1000 \
        -t 1000 \
        -n 0 \
        -c "/usr/local/bin/check_clamd.sh" \
        /usr/sbin/clamsmtpd -d 3 -f "${CLAMSMTPD_CONF_FILE}" 2>&1 \
            | awk -W Interactive '{print "[clamsmtpd] " $0}'
else
    sleep 86400
    exit 0
fi
