#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run clamd?
if [ "${ENABLE_CLAMAV}" = "true" ]; then
    /usr/sbin/clamsmtpd -d 2 -f "${CLAMSMTPD_CONF_FILE}" 2>&1 \
    | awk -W Interactive '{print "[clamsmtpd] " $0}'
else
    sleep 3600
    exit 0
fi
