#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run clamd?
if [ "${ENABLE_CLAMAV}" = "true" ]; then
    s6-notifyoncheck \
        -s 1000 \
        -t 1000 \
        -n 0 \
        -c "fdmove 1 3 clamdscan --stdout /VERSIONS" \
        /usr/local/sbin/clamd \
            --config-file="${CLAMAV_CLAMDCONF_FILE}" \
            --foreground 2>&1 \
            | awk -W Interactive '{print "[clamd] " $0}'
else
    sleep 86400
    exit 0
fi
