#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run freshclam?
if [ "${ENABLE_CLAMAV}" = "true" ]; then
    clamd \
        --foreground 2>&1 \
    | awk -W Interactive '{print "[clamd] " $0}'
else
    sleep 3600
    exit 0
fi
